# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:

  # jwt token auth
  # Add somewhere to your secrets yml
  # "config/secrets.yml"
  jwt_secret: '38af0483c50d39ebd023443sdfdghyuhvkfdeb58ea81a3fc366c1995c4da5bsuperrandomkey'
  jwt_expiration_hours: 18

  secret_key_base: 386b00fbb76ef48ecd55be7we98fdrt4534lk7b05e8f2dd472fa2f8b66a72af542e06ad9821ed232ea8c61321bd55ac826aaa501990d11b4fdf0068ac14f9c81b0d

test:
  secret_key_base: 8d82c8a77472ed87262e1ijkoes235f05856a665f8388b2490135c0a2b66abbfce9482da15f15888492992e3deba0648a4e6c31f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:

  # jwt token auth
  # Add somewhere to your secrets yml
  # "config/secrets.yml"
  jwt_secret: '62d2f8a46b9332c8ec62ba95d82509a7c79i7ytfdxwadyg58evenmoresuperrandomkey'
  jwt_expiration_hours: 18

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
